meta:
  environment: riak-cs-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: riak_z1
    instances: 1
    networks:
      - name: riak_cs1
        static_ips: (( static_ips(0) ))
  - name: riak_cs_z1
    instances: 1
    networks:
      - name: riak_cs1
        static_ips: (( static_ips(1) ))

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: riak_cs1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
      type: manual
    range: 10.244.2.0/30
    reserved:
    - 10.244.2.1
    static:
    - 10.244.2.2

  - cloud_properties:
      name: random
      type: manual
    range: 10.244.2.4/30
    reserved: []
    static:
    - 10.244.2.5-10.244.2.6

  - cloud_properties:
      name: random
      type: manual
    range: 10.244.2.8/30
    reserved: []
    static: []